import { StyleSheet } from 'react-native';
import { THEME } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.surface,
    padding: 24,
  },
  backButton: {
    marginBottom: 20,
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: THEME.primary,
    borderRadius: 16,
    alignSelf: 'flex-start',
    shadowColor: THEME.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  backButtonText: {
    color: THEME.background,
    fontSize: 16,
    fontWeight: '600',
  },
  titleInput: {
    backgroundColor: THEME.background,
    borderRadius: 16,
    padding: 18,
    marginBottom: 24,
    fontSize: 18,
    borderWidth: 1,
    borderColor: THEME.border,
    shadowColor: THEME.text.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  textInputStyle: {
    fontSize: 16,
    fontWeight: '500',
    color: THEME.text.primary,
  },
  scrollView: {
    flex: 1,
    marginBottom: 20,
  },
  emptyList: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#94A3B8',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  programItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: THEME.background,
    padding: 18,
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: THEME.text.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: THEME.border,
  },
  movementInfo: {
    flex: 1,
  },
  movementName: {
    fontSize: 16,
    fontWeight: '600',
    color: THEME.text.primary,
    marginBottom: 4,
  },
  setText: {
    fontSize: 14,
    color: THEME.text.secondary,
    marginTop: 4,
  },
  deleteButton: {
    backgroundColor: '#FF4F6E',
    padding: 12,
    borderRadius: 12,
    shadowColor: '#FF4F6E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  deleteButtonText: {
    color: THEME.background,
    fontSize: 14,
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: '#10B981',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    color: THEME.background,
    fontSize: 16,
    fontWeight: '700',
  },
  addMovementContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  movementInput: {
    flex: 2,
    backgroundColor: THEME.background,
    padding: 14,
    borderRadius: 12,
    marginRight: 12,
    borderWidth: 1,
    borderColor: THEME.border,
    shadowColor: THEME.text.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  setInput: {
    flex: 1,
    backgroundColor: THEME.background,
    padding: 14,
    borderRadius: 12,
    marginRight: 12,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: THEME.border,
    shadowColor: THEME.text.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  addButton: {
    backgroundColor: THEME.primary,
    padding: 14,
    borderRadius: 12,
    shadowColor: THEME.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  addButtonText: {
    color: THEME.background,
    fontSize: 14,
    fontWeight: '700',
  },
}); 