/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/eklesayfasi`; params?: Router.UnknownInputParams; } | { pathname: `/mygym`; params?: Router.UnknownInputParams; } | { pathname: `/Navigator`; params?: Router.UnknownInputParams; } | { pathname: `/ProgramDetay`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/styles/eklesayfasi.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mygym` | `/mygym`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/eklesayfasi`; params?: Router.UnknownOutputParams; } | { pathname: `/mygym`; params?: Router.UnknownOutputParams; } | { pathname: `/Navigator`; params?: Router.UnknownOutputParams; } | { pathname: `/ProgramDetay`; params?: Router.UnknownOutputParams; } | { pathname: `/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/styles/eklesayfasi.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mygym` | `/mygym`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/eklesayfasi${`?${string}` | `#${string}` | ''}` | `/mygym${`?${string}` | `#${string}` | ''}` | `/Navigator${`?${string}` | `#${string}` | ''}` | `/ProgramDetay${`?${string}` | `#${string}` | ''}` | `/theme${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/constants/theme${`?${string}` | `#${string}` | ''}` | `/styles/eklesayfasi.styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mygym${`?${string}` | `#${string}` | ''}` | `/mygym${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/eklesayfasi`; params?: Router.UnknownInputParams; } | { pathname: `/mygym`; params?: Router.UnknownInputParams; } | { pathname: `/Navigator`; params?: Router.UnknownInputParams; } | { pathname: `/ProgramDetay`; params?: Router.UnknownInputParams; } | { pathname: `/theme`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/styles/eklesayfasi.styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mygym` | `/mygym`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
